import "server-only";

import type { SupabaseClient } from "@supabase/supabase-js";
import { STARTING_AVATAR, STARTING_STATS, applyDeltas } from "./types";
import type {
  AvatarConfig,
  CharacterSnapshot,
  LlmScene,
  Stats,
} from "./types";
import type { Database, CharacterRow, NodeRow } from "@/lib/supabase/types";
import { timeBucketFor } from "./time";

const STARTING_GAME_TIME = "2026-03-02T08:30:00+11:00";

export type SbServer = SupabaseClient<Database>;

export interface ActiveScene {
  characterId: string;
  character: CharacterSnapshot;
  scene: {
    nodeId: string;
    sceneText: string;
    location: string;
    presetChoices: string[];
    authorUserId: string;
    authorName: string;
    authorHue: number;
    authorIsYou: boolean;
    gameTime: string;
  } | null;
}

/**
 * Fetch the most recently active character for `userId`, plus the node it's
 * currently sitting on. Returns null when the user has never played.
 */
export async function getActiveCharacter(
  supabase: SbServer,
  userId: string
): Promise<ActiveScene | null> {
  const { data: characters, error } = await supabase
    .from("characters")
    .select("*")
    .eq("user_id", userId)
    .order("created_at", { ascending: false })
    .limit(1);
  if (error) throw new Error(error.message);
  const character = characters?.[0];
  if (!character) return null;

  if (!character.current_node_id) {
    return {
      characterId: character.id,
      character: toCharacterSnapshot(character, userId, "you"),
      scene: null,
    };
  }

  const { data: nodeRow, error: nErr } = await supabase
    .from("nodes")
    .select("*")
    .eq("id", character.current_node_id)
    .maybeSingle();
  if (nErr) throw new Error(nErr.message);
  if (!nodeRow) {
    return {
      characterId: character.id,
      character: toCharacterSnapshot(character, userId, "you"),
      scene: null,
    };
  }

  const { data: authorProfile } = await supabase
    .from("profiles")
    .select("display_name, hue")
    .eq("id", nodeRow.author_user_id)
    .maybeSingle();

  return {
    characterId: character.id,
    character: toCharacterSnapshot(character, userId, "you"),
    scene: {
      nodeId: nodeRow.id,
      sceneText: nodeRow.scene_text,
      location: nodeRow.location,
      presetChoices: nodeRow.preset_choices,
      authorUserId: nodeRow.author_user_id,
      authorName: authorProfile?.display_name ?? "someone",
      authorHue: authorProfile?.hue ?? 50,
      authorIsYou: nodeRow.author_user_id === userId,
      gameTime: nodeRow.game_time,
    },
  };
}

/**
 * Create a new character (with default stats / avatar / starting location) for
 * `userId`. The root scene is generated by the caller and saved via
 * appendDbScene with parentId=null.
 */
export async function createCharacter(
  supabase: SbServer,
  userId: string,
  opts: { name?: string } = {}
): Promise<CharacterRow> {
  const profile = await supabase
    .from("profiles")
    .select("display_name")
    .eq("id", userId)
    .maybeSingle();
  const fallbackName = profile.data?.display_name ?? "Player";
  const name = opts.name?.trim() || fallbackName;

  const { data, error } = await supabase
    .from("characters")
    .insert({
      user_id: userId,
      name,
      avatar_config: { ...STARTING_AVATAR },
      stats: { ...STARTING_STATS },
      current_node_id: null,
    })
    .select("*")
    .single();
  if (error || !data) {
    throw new Error("Failed to create character: " + (error?.message ?? "unknown"));
  }
  return data;
}

/**
 * Persist a generated scene as a new node and roll the character forward.
 *
 * - parentId is whatever character.current_node_id is right now (may be null
 *   for the root, may be another user's node for a cross-user fork).
 * - The new node is authored by `userId`.
 * - location_index gets one row keyed by (location, time_bucket) so future
 *   crossing lookups are fast.
 */
export async function appendDbScene(
  supabase: SbServer,
  args: {
    userId: string;
    characterId: string;
    parentNodeId: string | null;
    chosenAction: string | null;
    scene: LlmScene;
  }
): Promise<{ node: NodeRow; character: CharacterRow }> {
  const { userId, characterId, parentNodeId, chosenAction, scene } = args;

  const { data: character, error: cErr } = await supabase
    .from("characters")
    .select("*")
    .eq("id", characterId)
    .single();
  if (cErr || !character) {
    throw new Error("Character not found: " + (cErr?.message ?? characterId));
  }
  if (character.user_id !== userId) {
    throw new Error("Character does not belong to current user");
  }

  const newStats = applyDeltas(character.stats, scene.statDeltas);
  const baseTime = character.current_node_id
    ? // base off the parent's game_time (we'll re-fetch to be precise)
      await fetchParentGameTime(supabase, parentNodeId)
    : new Date(STARTING_GAME_TIME);
  const newGameTime = new Date(
    baseTime.getTime() + scene.gameTimeAdvanceMinutes * 60 * 1000
  );
  const newAvatar: AvatarConfig = scene.avatarUpdates
    ? { ...character.avatar_config, ...scene.avatarUpdates }
    : character.avatar_config;

  const { data: node, error: nErr } = await supabase
    .from("nodes")
    .insert({
      parent_id: parentNodeId,
      author_user_id: userId,
      character_id: characterId,
      scene_text: scene.sceneText,
      location: scene.location,
      game_time: newGameTime.toISOString(),
      stats_snapshot: newStats,
      preset_choices: scene.presetChoices,
      chosen_action: chosenAction,
      is_public: true,
    })
    .select("*")
    .single();
  if (nErr || !node) {
    throw new Error("Failed to insert node: " + (nErr?.message ?? "unknown"));
  }

  const { data: charUpdated, error: uErr } = await supabase
    .from("characters")
    .update({
      current_node_id: node.id,
      stats: newStats,
      avatar_config: newAvatar,
    })
    .eq("id", characterId)
    .select("*")
    .single();
  if (uErr || !charUpdated) {
    throw new Error("Failed to update character: " + (uErr?.message ?? "unknown"));
  }

  // location_index: indexed lookup for crossing candidates.
  await supabase.from("location_index").insert({
    node_id: node.id,
    location: scene.location,
    time_bucket: timeBucketFor(newGameTime),
    character_id: characterId,
    author_user_id: userId,
    created_at: new Date().toISOString(),
  });

  return { node, character: charUpdated };
}

async function fetchParentGameTime(
  supabase: SbServer,
  parentNodeId: string | null
): Promise<Date> {
  if (!parentNodeId) return new Date(STARTING_GAME_TIME);
  const { data } = await supabase
    .from("nodes")
    .select("game_time")
    .eq("id", parentNodeId)
    .maybeSingle();
  if (!data) return new Date(STARTING_GAME_TIME);
  return new Date(data.game_time);
}

export function toCharacterSnapshot(
  c: CharacterRow,
  userId: string,
  authorNameFallback: string
): CharacterSnapshot & {
  currentNodeId: string | null;
  ownerUserId: string;
} {
  void userId; // currently unused but available for future logic
  const stats: Stats = c.stats;
  return {
    id: c.id,
    name: c.name,
    authorName: authorNameFallback,
    stats,
    avatarConfig: c.avatar_config,
    currentLocation: "(loading)",
    gameTime: new Date().toISOString(),
    currentNodeId: c.current_node_id,
    ownerUserId: c.user_id,
  };
}
