import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function Home() {
  return (
    <div className="flex flex-1 flex-col">
      <header className="border-b border-[var(--border)]/50 backdrop-blur-sm sticky top-0 z-10 bg-[var(--background)]/70">
        <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3 group">
            <div className="size-8 rounded-md bg-[var(--accent)] text-[var(--accent-ink)] grid place-items-center font-display font-bold">
              U
            </div>
            <div className="leading-tight">
              <div className="font-display font-semibold tracking-tight">
                UNSW Infinite
              </div>
              <div className="text-xs text-[var(--muted)]">
                Student Life Sim
              </div>
            </div>
          </Link>
          <nav className="flex items-center gap-2">
            <Link href="/explore">
              <Button variant="ghost" size="sm">
                Explore stories
              </Button>
            </Link>
            <Link href="/play">
              <Button variant="primary" size="sm">
                Start playing
              </Button>
            </Link>
          </nav>
        </div>
      </header>

      <main className="flex-1">
        <section className="mx-auto max-w-6xl px-6 py-20 lg:py-28">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full border border-[var(--border)] bg-[var(--surface)]/60 px-3 py-1 text-xs text-[var(--muted)] mb-6">
                <span className="size-1.5 rounded-full bg-[var(--accent)] animate-pulse" />
                Live-generated by AI on every click
              </div>
              <h1 className="font-display text-5xl lg:text-6xl font-semibold leading-[1.05] tracking-tight">
                Your UNSW life,
                <br />
                <span className="text-[var(--accent)]">infinitely generated.</span>
              </h1>
              <p className="mt-6 text-lg text-[var(--muted)] max-w-xl leading-relaxed">
                Wander the Quad, scrape through finals, join CSESoc, work
                shifts at Anchor — every scene is freshly written by AI in
                real time. Pick from four choices or type your own.
                Branch off, jump back, or hop into a friend&apos;s story.
              </p>
              <div className="mt-8 flex flex-wrap gap-3">
                <Link href="/play">
                  <Button size="lg">Start a new life</Button>
                </Link>
                <Link href="/explore">
                  <Button variant="outline" size="lg">
                    See other players&apos; stories
                  </Button>
                </Link>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3">
              {features.map((f) => (
                <Card key={f.title} className="p-5">
                  <div className="text-[var(--accent)] text-xs font-medium uppercase tracking-wider">
                    {f.tag}
                  </div>
                  <div className="font-display text-lg font-semibold mt-1">
                    {f.title}
                  </div>
                  <div className="text-sm text-[var(--muted)] mt-2 leading-relaxed">
                    {f.body}
                  </div>
                </Card>
              ))}
            </div>
          </div>
        </section>
      </main>

      <footer className="border-t border-[var(--border)]/50 py-6">
        <div className="mx-auto max-w-6xl px-6 text-xs text-[var(--muted)] flex items-center justify-between">
          <div>Made for UNSW students. Not affiliated with UNSW.</div>
          <div>Powered by Groq + Supabase</div>
        </div>
      </footer>
    </div>
  );
}

const features = [
  {
    tag: "Infinite",
    title: "Every page is new",
    body: "Click any choice; a fresh scene streams in instantly via Groq's ultra-fast LLM.",
  },
  {
    tag: "Branchable",
    title: "Jump back. Fork.",
    body: "Rewind to any earlier node and steer somewhere else, or branch off another player's story.",
  },
  {
    tag: "Social",
    title: "Crossing paths",
    body: "Bump into other players at the Roundhouse. Their recent choices ripple into your scene.",
  },
  {
    tag: "Yours",
    title: "Your story graph",
    body: "Every node is yours, colored with your hue. Forks from other players keep theirs.",
  },
];
